ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS sex text,
  ADD COLUMN IF NOT EXISTS height_cm numeric,
  ADD COLUMN IF NOT EXISTS weight_kg numeric,
  ADD COLUMN IF NOT EXISTS smoker text,
  ADD COLUMN IF NOT EXISTS alcohol text,
  ADD COLUMN IF NOT EXISTS exercise text,
  ADD COLUMN IF NOT EXISTS pregnant text,
  ADD COLUMN IF NOT EXISTS last_period date,
  ADD COLUMN IF NOT EXISTS cycle_length integer DEFAULT 28,
  ADD COLUMN IF NOT EXISTS periods_regular text,
  ADD COLUMN IF NOT EXISTS pcos_diagnosed text,
  ADD COLUMN IF NOT EXISTS hormonal_contraception text,
  ADD COLUMN IF NOT EXISTS contraception_type text,
  ADD COLUMN IF NOT EXISTS menopause text,
  ADD COLUMN IF NOT EXISTS emergency_contact_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
  ADD COLUMN IF NOT EXISTS emergency_contact_relationship text,
  ADD COLUMN IF NOT EXISTS doctor_name text,
  ADD COLUMN IF NOT EXISTS doctor_clinic text,
  ADD COLUMN IF NOT EXISTS insurance_provider text,
  ADD COLUMN IF NOT EXISTS insurance_member_id text,
  ADD COLUMN IF NOT EXISTS profile_completed boolean DEFAULT false;